username: "replaceme"
password: "replaceme"
database: "replaceme"
hostandport: "localhost:3306"
table: "tokens"
iptable: "tokenips"
iplimitmessage: "&cYou already generated a token using %player%! Contact owner if that isn't your account."